"""ACE external attestation core primitives."""

from .backblaze import (
    B2ApiError,
    B2AttestationClient,
    B2AttestationError,
    B2Config,
    B2ConfigurationError,
    B2ConflictError,
    B2Object,
    B2ObjectNotVisibleError,
    B2ObjectVersion,
    B2PostUploadVerificationError,
)
from .manifest import (
    ATTESTATION_CHAIN_ID,
    ATTESTATION_SCHEMA_VERSION,
    MANIFEST_GENERATOR_VERSION,
    AttestationRecord,
    AttestationSchemaError,
    attestation_record_from_event_row,
    canonical_attestation_json,
    parse_attestation_record,
)
from .sync import (
    AttestationLocalChainError,
    AttestationNamespaceError,
    AttestationRemoteSetMismatchError,
    AttestationRemoteVersionError,
    AttestationSyncError,
    AttestationSyncResult,
    derive_attestation_prefix,
    expected_attestation_objects,
    sync_attestation_records,
)

__all__ = [
    "ATTESTATION_CHAIN_ID",
    "ATTESTATION_SCHEMA_VERSION",
    "MANIFEST_GENERATOR_VERSION",
    "AttestationLocalChainError",
    "AttestationNamespaceError",
    "AttestationRecord",
    "AttestationRemoteSetMismatchError",
    "AttestationRemoteVersionError",
    "AttestationSchemaError",
    "AttestationSyncError",
    "AttestationSyncResult",
    "B2ApiError",
    "B2AttestationClient",
    "B2AttestationError",
    "B2Config",
    "B2ConfigurationError",
    "B2ConflictError",
    "B2Object",
    "B2ObjectNotVisibleError",
    "B2ObjectVersion",
    "B2PostUploadVerificationError",
    "attestation_record_from_event_row",
    "canonical_attestation_json",
    "derive_attestation_prefix",
    "expected_attestation_objects",
    "parse_attestation_record",
    "sync_attestation_records",
]
