version: '3.8'

services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://dealerscope:dealerscope@db:5432/dealerscope
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-change_me_in_production}
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: .
    command: ["celery", "-A", "webapp.celery_app", "worker", "--loglevel=info"]
    environment:
      - DATABASE_URL=postgresql://dealerscope:dealerscope@db:5432/dealerscope
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dealerscope
      - POSTGRES_USER=dealerscope
      - POSTGRES_PASSWORD=dealerscope
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: