# 🚀 DealerScope Production Security Configuration
# Advanced security, monitoring, and incident response implementation

security:
  # Security scanning configuration
  sast:
    enabled: true
    tools:
      - codeql
      - semgrep
      - bandit
    
  dependency_scanning:
    enabled: true
    auto_fix: false
    severity_threshold: medium
    
  secrets_detection:
    enabled: true
    tools:
      - trufflehog
      - gitleaks
    
  container_scanning:
    enabled: true
    base_image_updates: auto
    
# Monitoring and observability  
monitoring:
  metrics:
    enabled: true
    retention_days: 90
    
  logging:
    level: info
    structured: true
    retention_days: 30
    
  alerting:
    enabled: true
    channels:
      - slack
      - email
    
  slo_targets:
    availability: 99.9
    response_time_p95: 1000ms
    error_rate: 0.1
    
# Performance optimization
performance:
  caching:
    enabled: true
    strategy: redis
    ttl: 3600
    
  compression:
    enabled: true
    algorithms:
      - brotli
      - gzip
      
  cdn:
    enabled: true
    regions:
      - us-east-1
      - eu-west-1
      
# Infrastructure as Code
infrastructure:
  provider: github_actions
  environment_protection:
    production:
      required_reviewers: 2
      deployment_protection_rules:
        - wait_timer: 5
        
# Backup and disaster recovery
backup:
  strategy: automated
  frequency: daily
  retention: 30_days
  cross_region: true
  
disaster_recovery:
  rpo: 1_hour
  rto: 4_hours
  backup_regions:
    - us-west-2
    - eu-central-1