"""Canonical DealerScope business rules — single source of truth for economics and gates."""

from backend.business_rules.constants import (
    ALERTS_ENABLED_PRODUCTION_DEFAULT,
    DOS_SAVE_THRESHOLD,
    HIGH_RUST_STATES,
    HOT_DEAL_ALERT_THRESHOLD,
    HOT_DEAL_MIN_CONFIDENCE,
    HOT_DEAL_MIN_TRUST_SCORE,
    MIN_ROI_GOOD_PCT,
    MIN_ROI_HOT_PCT,
    PLATINUM_MIN_ROI_PER_DAY,
    PRICING_MATURITY_ALERT_ALLOWED,
    PROXY_PRICING_ALERT_ALLOWED,
    ROVER_RECOMMENDATION_THRESHOLD,
    RUST_STATE_NEW_VEHICLE_YEARS,
    STANDARD_BID_CEILING_PCT,
    STANDARD_MAX_MILEAGE,
    STANDARD_MAX_MILES_PER_YEAR,
    STANDARD_MIN_MARGIN,
    STANDARD_VEHICLE_MAX_AGE_YEARS,
    PREMIUM_BID_CEILING_PCT,
    PREMIUM_MAX_MILEAGE,
    PREMIUM_MIN_MARGIN,
    PREMIUM_VEHICLE_MAX_AGE_YEARS,
)
from backend.business_rules.gates import (
    bid_ceiling_pct_for_tier,
    current_calendar_year,
    determine_vehicle_tier,
    is_high_rust_state_rejected,
    min_margin_for_tier,
    passes_ceiling_and_margin,
    passes_ingest_margin_floor,
    passes_rover_economics,
)
from backend.business_rules.pricing import (
    PricingConfidence,
    classify_pricing_confidence,
    pricing_allows_hot_alert,
)

__all__ = [
    "ALERTS_ENABLED_PRODUCTION_DEFAULT",
    "DOS_SAVE_THRESHOLD",
    "HIGH_RUST_STATES",
    "HOT_DEAL_ALERT_THRESHOLD",
    "HOT_DEAL_MIN_CONFIDENCE",
    "HOT_DEAL_MIN_TRUST_SCORE",
    "MIN_ROI_GOOD_PCT",
    "MIN_ROI_HOT_PCT",
    "PLATINUM_MIN_ROI_PER_DAY",
    "PRICING_MATURITY_ALERT_ALLOWED",
    "PROXY_PRICING_ALERT_ALLOWED",
    "ROVER_RECOMMENDATION_THRESHOLD",
    "RUST_STATE_NEW_VEHICLE_YEARS",
    "STANDARD_BID_CEILING_PCT",
    "STANDARD_MAX_MILEAGE",
    "STANDARD_MAX_MILES_PER_YEAR",
    "STANDARD_MIN_MARGIN",
    "STANDARD_VEHICLE_MAX_AGE_YEARS",
    "PREMIUM_BID_CEILING_PCT",
    "PREMIUM_MAX_MILEAGE",
    "PREMIUM_MIN_MARGIN",
    "PREMIUM_VEHICLE_MAX_AGE_YEARS",
    "bid_ceiling_pct_for_tier",
    "current_calendar_year",
    "determine_vehicle_tier",
    "is_high_rust_state_rejected",
    "min_margin_for_tier",
    "passes_ceiling_and_margin",
    "passes_ingest_margin_floor",
    "passes_rover_economics",
    "PricingConfidence",
    "classify_pricing_confidence",
    "pricing_allows_hot_alert",
]
